##
# SSL Settings
##
ssl_certificate /etc/nginx/certificates/letsencrypt/kz.be-happy/fullchain.pem;
ssl_certificate_key /etc/nginx/certificates/letsencrypt/kz.be-happy/privkey.pem;
ssl_dhparam /etc/nginx/certificates/letsencrypt/ssl-dhparams.pem;

include /etc/nginx/certificates/letsencrypt/ssl-nginx.conf;
