include /etc/nginx/configurations/kz.be-happy.services_prime.conf;
include /etc/nginx/configurations/kz.be-happy.services_stage.conf;

# ---------------------------------------------------------
# PRIME
server {
    server_name be-happy.kz www.be-happy.kz;

    set $backend_kz_behappy_prime_web kz_behappy_prime_web_origin;
    include /etc/nginx/configurations/kz.be-happy.balancer_prime.conf;
    set $backend $backend_kz_behappy_prime_web;

    access_log /var/log/nginx/kz.be-happy.access.log;
    error_log /var/log/nginx/kz.be-happy.error.log;

    include /etc/nginx/snippets/kz.be-happy.common_settings.conf;
}

# ---------------------------------------------------------
# STAGE
server {
    server_name stage.be-happy.kz www.stage.be-happy.kz;

    set $backend_kz_behappy_stage_web kz_behappy_stage_web_origin;
    include /etc/nginx/configurations/kz.be-happy.balancer_stage.conf;
    set $backend $backend_kz_behappy_stage_web;

    access_log /var/log/nginx/kz.be-happy.access.log;
    error_log /var/log/nginx/kz.be-happy.error.log;

    include /etc/nginx/snippets/kz.be-happy.common_settings.conf;
}
